##PIPELINE FOR WORKPACKAGE 3
##P.aeruginosa bacteremias [FY2017-2019]
##LINKAGE OF DCS_HES_ONS birth registration
##Created by: Luisa Hallmaier-Wacker

###INITAL DATA PROCESSING#################################

source("./R/R_utilities.R")
timer2 <- Sys.time()

## Generate birth registration file [2010-2019]
##source("./R/birth_registrations.R")
##difftime(Sys.time(),timer2)


###DEFINING THE INITAL COHORT##############################

## Extract DCS data for P.aeruginosa
## extract is generated by DCS team (<1 years of age) 
source("./R/P.aeruginosa/pull_DCS_Paeruginosa.R")
difftime(Sys.time(),timer2)

## Generate P.aeruginosa Cohort
##Remove records of >1 year olds and update NHS number data found in SGSS
source("./R/P.aeruginosa/DSC_Paeruginosa_cohort.R")
difftime(Sys.time(),timer2)

remove(ECa, ECb, nhsvalid, SGSS, EC1_remove)

## Generate Frequency of Epidose by Financial Year 
##Output for WP3.1A
source("./R/P.aeruginosa/DCS_Paeruginosa_frequencyepisodes.R")
difftime(Sys.time(),timer2)


###LINKAGE PROCESS ########################################

## Linking cohort to birth registration and mHES records
source("./R/P.aeruginosa/DCS-BR-mHES_linkage_Paeruginosa.R")
difftime(Sys.time(),timer2)

remove(S1,S2,S3,S4,S5, EC1_BR_mHES_1, EC1_BR_mHES_2, EC1_BR_mHES_3, 
       mHES, mHES2, mHES_delivery, mHES2_delivery, BR, mTraced, nhsvalid,
       EC1_BR_mTrace_nomatch, EC1_BR_unlink, EC1_BR_mHES_0, 
       EC1_BR_mHES_unliked_HESrecord, EC1_BR_mHES_unliked_noHESrecord)


###OUTPUT GENERATION########################################

## Primary Focus Bacteraemia
##Output for WP3.2A
source("./R/P.aeruginosa/primary_focus_of_bacteraemia.R")
difftime(Sys.time(),timer2)

## Gestational Age
##Output for WP3.2B
source("./R/P.aeruginosa/gestational_age.R")
difftime(Sys.time(),timer2)

## Birth Weight
##Output for WP3.2C
source("./R/P.aeruginosa/birth_weight.R")
difftime(Sys.time(),timer2)

## Multiples
##Output for WP3.2D
source("./R/P.aeruginosa/multiple_birth_count.R")
difftime(Sys.time(),timer2)

## Mother's ethnicity
##Output for WP3.2E
source("./R/P.aeruginosa/mothers_ethnicity.R")
difftime(Sys.time(),timer2)

## Mother's social deprevation
##Output for WP3.2F
source("./R/P.aeruginosa/social_deprivation.R")
difftime(Sys.time(),timer2)

## Mother's age
##Output for WP3.2G
source("./R/P.aeruginosa/maternal_age.R")
difftime(Sys.time(),timer2)

## Recurrence (>14 days between episodes)
##Output for WP3.3C
source("./R/P.aeruginosa/recurrence.R")
difftime(Sys.time(),timer2)

## Mortality
##Output for WP3.3E
source("./R/P.aeruginosa/mortality.R")
difftime(Sys.time(),timer2)


###INFANT HES RECORDS###

## Grouping infant HES records into spells
source("./R/P.aeruginosa/HES_spells.R")
difftime(Sys.time(),timer2)

## Linkage of DCS to infant HES (iHES)
## Output for WP3.2J-L and 3.3A
source("./R/P.aeruginosa/DSC_iHES_linkage.R")
difftime(Sys.time(),timer2)
